"""add is_pinned to session

Revision ID: 9abf112cf4ce
Revises: 9e90e78d4681
Create Date: 2026-05-06 11:32:00.753055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abf112cf4ce'
down_revision: Union[str, Sequence[str], None] = '9e90e78d4681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'is_pinned')
    # ### end Alembic commands ###
